name: Padavan手动云编译

on:
  workflow_dispatch:
    inputs:
      production:
        description: 设置固件型号：
        default: "K2P PSG1218 XY-C1 MSG1500 NEWIFI3"
        required: false
      cloneurl:
        description: 设置源码地址：
        default: "https://github.com/immortalwrt/padavan.git"
        required: false
      release:
        description: 是否发布到Release？
        default: 'yes'
        required: false

env:
  IMAGES: /opt/images
  RT_N56U: /opt/rt-n56u
  TRUNK: /opt/rt-n56u/trunk
  URL1: "https://github.com/weln2020/manual-action-padavan"
  URL2: "https://www.right.com.cn/forum/thread-6896728-1-1.html"

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: 同步主存储库
      uses: actions/checkout@master
    - name: 初始环境设置
      run: |
        sudo apt-get update
        sudo apt install unzip libtool-bin curl cmake gperf gawk flex bison nano xxd \
        fakeroot kmod cpio git python3-docutils gettext automake autopoint \
        texinfo build-essential help2man pkg-config zlib1g-dev libgmp3-dev \
        libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget libc-dev-bin > /dev/null
    - name: 生成版本号
      run: |
        whoami
        id
        echo "DATE=$(TZ='Asia/Shanghai' date '+%Y.%m.%d-%H%M')" >> $GITHUB_ENV
        val=$(echo ${{ github.event.inputs.production }} | sed 's/ /-/')
        echo "NAME=Padavan-${val}" >> $GITHUB_ENV
        ip addr
        echo "${{ env.NAME }}"
    - name: 下载源码
      run: |
        mkdir -p $IMAGES
        echo 开始编译时间： >> $IMAGES/readme.txt
        TZ='Asia/Shanghai' date '+%Y-%m-%d %H:%M:%S' >> $IMAGES/readme.txt
        git clone --depth=1 ${{ github.event.inputs.cloneurl }} $RT_N56U > /dev/null
        cd $RT_N56U/toolchain-mipsel
        sh dl_toolchain.sh > /dev/null
    - name: 自定义配置
      run: |
        cp -f ./defaults.h $TRUNK/user/shared
        cp -f ./versions.inc $TRUNK
        valtime="\\1 footer_code +='编译日期: ${{ env.DATE }} by <a href=\"$URL1\" target=\"blank\">WELN</a> \& <a href=\"$URL2\" target=\"blank\">恩山论坛</a> \& <a href=\"${{ github.event.inputs.cloneurl }}\" target=\"blank\">源代码</a><br>';"
        sed -i "s#\(.*Non-Commercial Use Only[^;]*;\).*#$valtime#" $TRUNK/user/www/n56u_ribbon_fixed/state.js
    - name: 开始编译
      run: |
        for m in ${{ github.event.inputs.production }}; do
          cp -f config/$m.config $TRUNK/configs/templates
          pushd $TRUNK
          echo "::group::开始编译 ${m}..."
          sudo ./clear_tree || echo
          sudo ./build_firmware_modify $m > /dev/null
          ls -l images
          sudo mv -f images/*.trx $IMAGES
          echo "::endgroup::"
          popd
        done
    - name: 收集信息
      run: |
        cd $IMAGES
        echo 完成编译时间： >> readme.txt
        TZ='Asia/Shanghai'  date  '+%Y-%m-%d %H:%M:%S' >> readme.txt
        echo >> readme.txt
        echo 源码信息： >> readme.txt
        pushd $RT_N56U
        git ls-remote --get-url origin >> $IMAGES/readme.txt
        git log --shortstat >> $IMAGES/readme.txt
        popd
        echo >> readme.txt
        echo md5校验值： >> readme.txt
        for m in *.trx
        do
          mv -fv "$m" "${m%.*}_${{ env.DATE }}.trx"
        done
        md5sum *.trx >> readme.txt || echo
        ls -l
    - name: 上传固件到Artifacts
      if: true
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.NAME }}
        path: ${{ env.IMAGES }}
    - name: 发布固件到Release
      if: ${{ github.event.inputs.release == 'yes' }}
      uses: softprops/action-gh-release@v1
      with:
        name: ${{ env.NAME }}
        tag_name: ${{ env.DATE }}
        body_path: ${{ env.IMAGES }}/readme.txt
        draft: false
        prerelease: false
        files: ${{ env.IMAGES }}/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
